a = "TGCTGTCTTGGCTGCTGCCATGTAAGATGTGACTTTGCTCCTCCTTGCCTTCCACAATGATTGTGAGGCCTCCCTAACCATGTGGAACTATGAGTCAATTAAACTTCTTTCCTTTATAAATCACTCAGACTCAGGTATATCTTTATTAGCAGTCTGAGAACAGACTAATACACTCTTTTTATATAACTAATCACCAAATTCTAGTTTTCCCCTTCCAGATGTCTCTAGATTTGTCCTTCTTTTGATATTTTTATCACCCTGTTTCAGCCTGCCATCCAGTGCACACTTATTGGACACCATCTCCTAGGAACAACATTAGCTGATGGGGGATATATCAAGGATTAACCCAATCCCTGCCTTCAGGGAGCTAACCAGCAGGGAGATGGTCAAGTAAACAGCAGCCATAAGCAGGGTGTGGTAAATGCTGTTTAGAGGCTGTGCAGGGGTGCTATGGAGCACAGAGAACTTGAAAACCTAGCCCTGAGGGGCCTCTGCACATAGAGGATTCAGATCTGGAGTC"
n = len(a)
b = "CCTATAACTTAAAGTATAATAAAAAAAGTTTGCAATGATTGAATAGACATCTCTCAAAAAAGGATATCCAAATGGTCAACAGGTATGTGAAAATTACTGCGTGTCCTTAAGCATAAGGGAAATGCAAATCAAAACCACAAAGAAATACCATCTCACCCCAGTTAAGATAGCTACTATCAAAAAGACAAAAAATAACATATGCTGGCAAGGATGTAGAGAAGTGAAAAGACTAGTAGTACACTGTGGGTTGGAATGTAAATTAGTACAGCCACTATGGAAAACAAGAGTGGAGACTCCTCAAAAAAAATAAAATTGGATTTACCATATGATCTAGAAATCTTATCACTGAATATATCTGAAAGAAAATAAATCAGTATATTGAAGAGATATCTGCACTCCCGTATTTATTGCAACACTGTTCACAACAGCCAAGATATGTAAATGATTTCATAACTGTCCATTAGCAGATGAATGGATAAATAAATATGGTATGTATGCACAGTAAATCGTTATTCAGCCATAAAAAAAGAATGAAATCCCATCACTGGAGTCATTATGTTAAGTGAAAAAAGGCAGCATGGAAAGACAAATATGGTTTGTCCTTCCTCATATGCAGGAGCTAAAAATATTGATCTCACAGAGGCAGAGAATACAGTGGTACTTACC"
m = len(b)

dp = []
p = []
for i in range(n + 1):
    dp.append([1 << 32 for j in range(m + 1)])
    p.append([-1 for j in range(m + 1)])

dp[0][0] = 0
for i in range(1, n + 1):
    dp[i][0] = i
    p[i][0] = (i - 1, 0)

for j in range(1, m + 1):
    dp[0][j] = j
    p[0][j] = (j - 1, 0)

for i in range(1, n + 1):
    for j in range(1, m + 1):
        if a[i - 1] == b[j - 1]:
            p[i][j] = (i - 1, j - 1)
            dp[i][j] = dp[i - 1][j - 1] + 1
        if dp[i][j] > dp[i - 1][j] + 1:
            dp[i][j] = dp[i - 1][j] + 1
            p[i][j] = (i - 1, j)
        if dp[i][j] > dp[i][j - 1] + 1:
            dp[i][j] = dp[i][j - 1] + 1
            p[i][j] = (i, j - 1)

curr = (n, m)
res = ""
while curr != -1:
    if p[curr[0]][curr[1]] != -1:
        if p[curr[0]][curr[1]][0] == curr[0] - 1:
            res += a[curr[0] - 1]
        else:
            res += b[curr[1] - 1]
    curr = p[curr[0]][curr[1]]
res = res[::-1]

i, j = 0, 0
a_aligned = ""
b_aligned = ""
for k in range(len(res)):
    if i < len(a) and res[k] == a[i]:
        a_aligned += a[i]
        i += 1
    else:
        a_aligned += "-"

    if j < len(b) and res[k] == b[j]:
        b_aligned += b[j]
        j += 1
    else:
        b_aligned += "-"

print(res)
print(b_aligned)
print(a_aligned)
